# Cloud Build設定ファイル
# GitHub Actions経由でトリガーされる想定

steps:
  # ステップ1: 依存関係のインストール
  - name: 'gcr.io/cloud-builders/go'
    args: ['mod', 'download']
    env:
      - 'GO111MODULE=on'
    id: 'download-deps'

  # ステップ2: テスト実行
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', './...', '-v']
    env:
      - 'GO111MODULE=on'
    id: 'run-tests'
    waitFor: ['download-deps']

  # ステップ3: Cloud Functionsデプロイ（HTTPトリガー）
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - '${_FUNCTION_NAME}'
      - '--gen2'
      - '--runtime=go122'
      - '--region=${_REGION}'
      - '--source=.'
      - '--entry-point=CuratorHandler'
      - '--trigger-http'
      - '--no-allow-unauthenticated'
      - '--service-account=${_SERVICE_ACCOUNT}'
      - '--memory=512Mi'
      - '--timeout=3600s'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--set-env-vars=CONFIG_URL=https://raw.githubusercontent.com/${_GITHUB_REPO}/main/config.json,GCP_PROJECT_ID=${PROJECT_ID},GEMINI_API_KEY_SECRET=gemini-api-key,DISCORD_WEBHOOK_SECRET=discord-webhook-url'
      - '--project=${PROJECT_ID}'
    id: 'deploy-function'
    waitFor: ['run-tests']

# デフォルト値
substitutions:
  _FUNCTION_NAME: 'rss-article-curator'
  _REGION: 'asia-northeast1'
  _SERVICE_ACCOUNT: 'rss-curator-function@rss-article-curator-prod.iam.gserviceaccount.com'
  _GITHUB_REPO: 'kaka0913/discord-article-bot'

# タイムアウト設定
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
